package com.warrioraspirants.app;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
 int NAVY=Color.rgb(12,24,52),RED=Color.rgb(210,38,45),BG=Color.rgb(246,247,250),WHITE=Color.WHITE,DARK=Color.rgb(35,40,50),MUTED=Color.rgb(105,112,125);
 LinearLayout root,body; TextView pageTitle,progress; ArrayList<String> mistakes=new ArrayList<>(); ProgressStore store;
 public void onCreate(Bundle b){super.onCreate(b); store=new ProgressStore(this); mistakes=store.mistakes(); splash();}
 TextView text(String s,float size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(18,7,18,7);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
 GradientDrawable shape(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(r);return g;}
 Button action(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(NAVY);b.setAllCaps(false);b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(18,0,18,0);b.setBackground(shape(WHITE,24));b.setElevation(3);b.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,64);p.setMargins(0,6,0,6);body.addView(b,p);return b;}
 void splash(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setGravity(Gravity.CENTER);l.setPadding(28,20,28,20);l.setBackgroundColor(NAVY);ImageView logo=new ImageView(this);logo.setImageResource(com.warrioraspirants.app.R.drawable.warrior_icon);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);l.addView(logo,new LinearLayout.LayoutParams(-1,250));TextView a=text("WARRIOR ASPIRANTS",27,WHITE,true),q=text("Build the Empire.\nThe Queen Will Come.",17,Color.LTGRAY,true);a.setGravity(17);q.setGravity(17);l.addView(a);l.addView(q);setContentView(l);logo.setAlpha(0);a.setAlpha(0);q.setAlpha(0);logo.animate().alpha(1).setDuration(700);a.animate().alpha(1).setStartDelay(350).setDuration(650);q.animate().alpha(1).setStartDelay(600).setDuration(650);new Handler().postDelayed(this::home,2300);}
 void home(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
  LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(18,15,18,12);head.setBackgroundColor(NAVY);
  LinearLayout brand=new LinearLayout(this);brand.setGravity(Gravity.CENTER_VERTICAL);ImageView icon=new ImageView(this);icon.setImageResource(com.warrioraspirants.app.R.drawable.warrior_icon);icon.setScaleType(ImageView.ScaleType.CENTER_INSIDE);brand.addView(icon,new LinearLayout.LayoutParams(58,58));LinearLayout brandText=new LinearLayout(this);brandText.setOrientation(LinearLayout.VERTICAL);brandText.addView(text("WARRIOR ASPIRANTS",20,WHITE,true));brandText.addView(text("Knowledge for Victory",11,Color.LTGRAY,false));brand.addView(brandText,new LinearLayout.LayoutParams(0,58,1));head.addView(brand);head.addView(text("Today’s mission • Learn → Practice → Analyze",13,Color.LTGRAY,false));root.addView(head);
  body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(14,12,14,14);ScrollView sc=new ScrollView(this);sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout nav=new LinearLayout(this);nav.setPadding(3,2,3,2);nav.setBackgroundColor(WHITE);String[] n={"Home","Study","Practice","Current Affairs","Profile"};for(String x:n){Button b=new Button(this);b.setText(x);b.setTextSize(9);b.setTextColor(NAVY);b.setAllCaps(false);b.setOnClickListener(v->page(x));nav.addView(b,new LinearLayout.LayoutParams(0,62,1));}root.addView(nav);setContentView(root);page("Home");}
 void page(String p){body.removeAllViews();body.addView(text(p,25,NAVY,true));
  if(p.equals("Home")){hero("TODAY'S MISSION","Start with Maths → Number System\n30 min Theory • 15 min Practice • 10 min Revision");card("YOUR PROGRESS","Preparation "+store.prep()+"%","🔥 Streak "+store.streak()+" days   •   XP "+store.xp()+"   •   Level "+store.level()+"   •   Accuracy "+store.accuracy()+"%");section("QUICK START");action("📐 Continue Maths — Number System",v->lesson("Number System"));action("🧠 10 Question Practice",v->practice());action("🤖 Ask Fighter AI",v->fighter());action("📕 Mistake Book",v->mistakes());action("📤 Share Warrior Aspirants",v->shareApp());}
  else if(p.equals("Study")){card("STUDY ROOM","SSC CGL • Railway • UP SI","Choose a subject. Every subject follows: Theory → Examples → Practice → PYQ → Revision");subject("📐","Maths","Beginner → Advanced",v->topics("Maths"));subject("🧠","Reasoning","Concepts + patterns + speed",v->topics("Reasoning"));subject("🔤","English","Grammar + vocabulary + comprehension",v->topics("English"));subject("🌍","GK / GS","History • Geography • Polity • Science",v->topics("GK / GS"));}
  else if(p.equals("Practice")){card("PRACTICE ARENA","Choose your mission","10 / 20 / 50 questions • Timer • Accuracy");action("⚡ Quick Practice — 10 Questions",v->practice());action("🎯 Topic Practice",v->topics("Practice Topics"));action("🎯 PYQ Engine",v->pyq());action("🏆 Mock Test",v->mock());action("📕 Mistake Book",v->mistakes());}
  else if(p.equals("Current Affairs")){card("CURRENT AFFAIRS","Daily → Weekly → Monthly","Live/current content will be connected through the update module.");action("📅 Daily Current Affairs",v->ca("Daily Current Affairs"));action("📚 Weekly Revision",v->ca("Weekly Revision"));action("🗓 Monthly One-Liners",v->ca("Monthly One-Liners"));action("❓ Daily Quiz",v->ca("Current Affairs Quiz"));}
  else {card("WARRIOR PROFILE","Level 1 • XP 0 • Streak 0 days","Target: SSC CGL 2027 • Railway • UP SI");action("⚙️ Preparation Settings",v->settings());action("📊 My Progress",v->progress());}
 }
 void section(String s){body.addView(text(s,13,RED,true));}
 void card(String h,String sub,String val){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(8,10,8,10);c.setBackground(shape(WHITE,26));c.setElevation(4);c.addView(text(h,16,RED,true));c.addView(text(sub,17,DARK,true));c.addView(text(val,13,MUTED,false));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,7,0,8);body.addView(c,p);}
 void hero(String h,String b){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(12,12,12,12);c.setBackground(shape(NAVY,26));c.addView(text(h,12,Color.LTGRAY,true));c.addView(text(b,18,WHITE,true));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,5,0,10);body.addView(c,p);}
 void subject(String icon,String name,String sub,View.OnClickListener l){LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(8,8,8,8);c.setBackground(shape(WHITE,24));c.setElevation(3);TextView i=text(icon,25,RED,true);TextView n=text(name+"\n"+sub,16,DARK,true);c.addView(i,new LinearLayout.LayoutParams(55,72));c.addView(n,new LinearLayout.LayoutParams(0,72,1));Button go=new Button(this);go.setText("›");go.setTextSize(25);go.setTextColor(RED);go.setBackgroundColor(Color.TRANSPARENT);go.setOnClickListener(l);c.addView(go,new LinearLayout.LayoutParams(55,72));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,78);p.setMargins(0,6,0,6);body.addView(c,p);}
 void topics(String s){body.removeAllViews();body.addView(text(s+" • Topics",24,NAVY,true));
  if(s.equals("Maths")){topic("01","Number System","Basics, divisibility, HCF/LCM",v->lesson("Number System"));topic("02","Percentage","Basic percentage, increase/decrease",v->lesson("Percentage"));topic("03","Ratio & Proportion","Ratio, proportion and applications",v->lesson("Ratio & Proportion"));topic("04","Average","Mean and weighted average",v->lesson("Average"));topic("05","Profit & Loss","CP, SP, profit/loss percentage",v->lesson("Profit & Loss"));topic("06","Time & Work","Work efficiency and combined work",v->lesson("Time & Work"));topic("07","Time, Speed & Distance","Speed, distance, trains",v->lesson("Time, Speed & Distance"));topic("08","Algebra","Identities and basic equations",v->lesson("Algebra"));topic("09","Geometry & Mensuration","Lines, angles, triangles, areas",v->lesson("Geometry & Mensuration"));topic("10","Trigonometry","Ratios and standard values",v->lesson("Trigonometry"));}
  else if(s.equals("Reasoning")){topic("01","Analogy","Find the same relationship",v->lesson("Analogy"));topic("02","Classification","Find the odd one out",v->lesson("Classification"));topic("03","Series","Number, alphabet and figure series",v->lesson("Series"));topic("04","Coding-Decoding","Letter/number coding patterns",v->lesson("Coding-Decoding"));topic("05","Blood Relation","Family relationship problems",v->lesson("Blood Relation"));topic("06","Direction & Distance","Directions and shortest path",v->lesson("Direction & Distance"));topic("07","Syllogism","Statements and conclusions",v->lesson("Syllogism"));topic("08","Venn Diagram","Set relationships",v->lesson("Venn Diagram"));}
  else if(s.equals("English")){topic("01","Parts of Speech","Noun, pronoun, verb, adjective...",v->lesson("Parts of Speech"));topic("02","Tenses","Present, past and future",v->lesson("Tenses"));topic("03","Subject-Verb Agreement","Correct verb with subject",v->lesson("Subject-Verb Agreement"));topic("04","Articles","A, An, The",v->lesson("Articles"));topic("05","Prepositions","Usage and common errors",v->lesson("Prepositions"));topic("06","Active & Passive Voice","Voice transformation",v->lesson("Active & Passive Voice"));topic("07","Narration","Direct and indirect speech",v->lesson("Narration"));topic("08","Error Detection","Grammar-based errors",v->lesson("Error Detection"));}
  else {topic("01","History","Ancient, Medieval, Modern India",v->lesson("History"));topic("02","Geography","India and world geography",v->lesson("Geography"));topic("03","Polity","Constitution and governance",v->lesson("Polity"));topic("04","Economy","Basic economic concepts",v->lesson("Economy"));topic("05","Physics","Motion, work, energy, electricity",v->lesson("Physics"));topic("06","Chemistry","Matter, atoms, reactions",v->lesson("Chemistry"));topic("07","Biology","Cells, human body, plants",v->lesson("Biology"));}
  action("← Back to Study",v->page("Study"));
 }
 void topic(String no,String name,String sub,View.OnClickListener l){LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(8,6,8,6);c.setBackground(shape(WHITE,22));TextView num=text(no,13,RED,true);c.addView(num,new LinearLayout.LayoutParams(48,62));TextView n=text(name+"\n"+sub,15,DARK,true);c.addView(n,new LinearLayout.LayoutParams(0,62,1));Button b=new Button(this);b.setText("OPEN");b.setTextSize(10);b.setTextColor(RED);b.setAllCaps(false);b.setBackgroundColor(Color.TRANSPARENT);b.setOnClickListener(l);c.addView(b,new LinearLayout.LayoutParams(65,62));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,68);p.setMargins(0,5,0,5);body.addView(c,p);}
 void lesson(String topic){body.removeAllViews();body.addView(text(topic,25,NAVY,true));card("LESSON","Theory + Example + Trick + Practice","Beginner-friendly explanation. Read → understand → solve.");String th=theory(topic);body.addView(text("THEORY",14,RED,true));body.addView(text(th,16,DARK,false));body.addView(text("WORKED EXAMPLE",14,RED,true));body.addView(text(example(topic),16,DARK,false));body.addView(text("QUICK TRICK",14,RED,true));body.addView(text(trick(topic),16,DARK,false));action("▶ Start Practice",v->practiceTopic(topic));action("🎯 Open PYQs",v->pyqTopic(topic));action("← Back",v->topics(topic.equals("Maths")?"Maths":topic.equals("Reasoning")?"Reasoning":topic.equals("English")?"English":"GK / GS"));}
 StudyContent.Lesson material(String topic){ return StudyContent.get(topic); }
 String theory(String t){ return material(t).theory; }
 String example(String t){ return material(t).example; }
 String trick(String t){ return material(t).trick; }

 void practice(){practiceTopic("Mixed Practice");}
 void practiceTopic(String topic){body.removeAllViews();body.addView(text("Practice • "+topic,24,NAVY,true));card("QUESTION 1","A number is 20% of 250. What is the number?","Choose one option.");String[] o={"25","40","50","60"};for(String x:o){action(x,v->{if(x.equals("50")){store.addResult(true);mistakes=store.mistakes();toast("Correct! +10 XP • Progress saved");}else{store.addResult(false);store.saveMistake(topic+" — 20% of 250");mistakes=store.mistakes();toast("Wrong. Added to saved Mistake Book.");}});}action("Next Question",v->toast("More questions will load here."));}
 void pyq(){body.removeAllViews();body.addView(text("PYQ ENGINE",24,NAVY,true));card("FILTER","Exam • Year • Subject • Topic","Verified PYQs will be added with source, answer and explanation.");action("SSC CGL → Maths",v->pyqTopic("Maths"));action("SSC CGL → Reasoning",v->pyqTopic("Reasoning"));action("SSC CGL → English",v->pyqTopic("English"));action("SSC CGL → General Awareness",v->pyqTopic("GK / GS"));}
 void pyqTopic(String t){body.removeAllViews();body.addView(text("PYQ • "+t,24,NAVY,true));card("QUESTION BANK","Topic-wise previous-year questions","Each question should contain year, shift/source, options, verified answer and explanation.");action("Start Topic PYQ",v->practiceTopic(t));action("← Back",v->pyq());}
 void mock(){body.removeAllViews();body.addView(text("MOCK TESTS",24,NAVY,true));card("FULL MOCK","SSC CGL-style practice","Timer • section analysis • accuracy • attempted/unattempted • mistakes");action("Start Demo Mock",v->practiceTopic("Mock Test"));action("← Back",v->page("Practice"));}
 void mistakes(){body.removeAllViews();body.addView(text("MISTAKE BOOK",24,NAVY,true));if(mistakes.size()==0)card("EMPTY","No mistakes saved yet","Wrong practice questions will appear here automatically.");else for(String m:mistakes)card("REVISE",m,"Open question → understand → retry");action("← Back",v->page("Practice"));}
 void fighter(){body.removeAllViews();body.addView(text("FIGHTER AI",24,NAVY,true));hero("YOUR STUDY PARTNER","Explain • Solve • Quiz • Revise");card("ASK FIGHTER","Examples:","“Percentage basic se samjhao”\n“Is question ka solution batao”\n“Meri galti explain karo”\n“10 Maths questions do”");EditText e=new EditText(this);e.setHint("Ask Fighter...");e.setTextSize(15);e.setPadding(18,5,18,5);e.setBackground(shape(WHITE,22));body.addView(e,new LinearLayout.LayoutParams(-1,58));action("Send",v->toast("Fighter backend will answer after AI API integration."));}
 void ca(String s){body.removeAllViews();body.addView(text(s,24,NAVY,true));card("CONTENT MODULE","Fresh verified updates","This screen is ready for the live content pipeline. Current-affairs facts should be sourced and dated.");action("← Back",v->page("Current Affairs"));}
 void settings(){body.removeAllViews();body.addView(text("SETTINGS",24,NAVY,true));card("TARGET EXAMS","SSC CGL 2027","Railway • UP SI");card("DAILY TARGET","2 hours","Can be expanded to a personalised planner.");action("🗑 Reset saved progress",v->{new AlertDialog.Builder(this).setTitle("Reset progress?").setMessage("XP, solved questions and Mistake Book will be cleared on this device.").setNegativeButton("Cancel",null).setPositiveButton("Reset",(d,w)->{getSharedPreferences("warrior_progress",MODE_PRIVATE).edit().clear().apply();store=new ProgressStore(this);mistakes=store.mistakes();toast("Progress reset");page("Profile");}).show();});action("← Back",v->page("Profile"));}
 void progress(){body.removeAllViews();body.addView(text("MY PROGRESS",24,NAVY,true));card("LEVEL "+store.level(),"XP "+store.xp(),"Preparation "+store.prep()+"% • Accuracy "+store.accuracy()+"% • Streak "+store.streak()+" days");card("LEARNING LOOP","Learn → Practice → Analyze → Improve","Your XP, solved questions and Mistake Book are saved on this device.");action("← Back",v->page("Profile"));}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}