package com.warrioraspirants.app;

import android.app.*;
import android.os.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
    int NAVY=Color.rgb(9,20,45), RED=Color.rgb(220,45,52), BG=Color.rgb(246,248,252), WHITE=Color.WHITE, DARK=Color.rgb(28,35,48), MUTED=Color.rgb(105,114,130);
    LinearLayout root,body; ProgressStore store; ArrayList<String> mistakes=new ArrayList<>();
    public void onCreate(Bundle b){super.onCreate(b);store=new ProgressStore(this);mistakes=store.mistakes();splash();}
    TextView text(String s,float size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(18,5,18,5);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    GradientDrawable shape(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(r);return g;}
    GradientDrawable stroke(int fill,int line,float r){GradientDrawable g=shape(fill,r);g.setStroke(1,line);return g;}
    void animateView(View v,int delay){v.setAlpha(0f);v.setTranslationY(22f);v.animate().alpha(1f).translationY(0f).setStartDelay(delay).setDuration(420).setInterpolator(new android.view.animation.DecelerateInterpolator()).start();}
    void press(View v){v.animate().scaleX(.975f).scaleY(.975f).setDuration(70).withEndAction(()->v.animate().scaleX(1f).scaleY(1f).setDuration(120).start()).start();}
    Button action(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(NAVY);b.setAllCaps(false);b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(18,0,18,0);b.setBackground(stroke(WHITE,Color.rgb(230,233,240),20));b.setElevation(2);b.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,58);p.setMargins(0,5,0,5);body.addView(b,p);animateView(b,body.getChildCount()*28);b.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN)press(v);return false;});return b;}
    void splash(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setGravity(Gravity.CENTER);l.setPadding(28,20,28,20);l.setBackgroundColor(NAVY);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.warrior_icon);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);l.addView(logo,new LinearLayout.LayoutParams(-1,230));TextView a=text("WARRIOR ASPIRANTS",27,WHITE,true),q=text("Build the Empire.\nThe Queen Will Come.",17,Color.LTGRAY,true);a.setGravity(17);q.setGravity(17);l.addView(a);l.addView(q);setContentView(l);logo.setScaleX(.75f);logo.setScaleY(.75f);logo.setAlpha(0);a.setAlpha(0);q.setAlpha(0);logo.animate().alpha(1).scaleX(1).scaleY(1).setDuration(750);a.animate().alpha(1).setStartDelay(350).setDuration(650);q.animate().alpha(1).setStartDelay(600).setDuration(650);new Handler().postDelayed(this::home,2300);}
    void home(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(18,14,18,14);head.setBackground(shape(NAVY,0));LinearLayout brand=new LinearLayout(this);brand.setGravity(Gravity.CENTER_VERTICAL);ImageView icon=new ImageView(this);icon.setImageResource(R.drawable.warrior_icon);icon.setScaleType(ImageView.ScaleType.CENTER_INSIDE);brand.addView(icon,new LinearLayout.LayoutParams(54,54));LinearLayout bt=new LinearLayout(this);bt.setOrientation(LinearLayout.VERTICAL);bt.addView(text("WARRIOR ASPIRANTS",19,WHITE,true));bt.addView(text("KNOWLEDGE FOR VICTORY",10,Color.rgb(190,201,225),false));brand.addView(bt,new LinearLayout.LayoutParams(0,54,1));head.addView(brand);root.addView(head);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(16,14,16,18);ScrollView sc=new ScrollView(this);sc.addView(body);sc.setClipToPadding(false);sc.setOverScrollMode(View.OVER_SCROLL_NEVER);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);nav.setPadding(8,7,8,7);nav.setBackgroundColor(WHITE);nav.setElevation(10);String[] n={"⌂  Home","▣  Study","⚡  Practice","◷  Current","◉  Profile"};for(String x:n){Button b=new Button(this);b.setText(x);b.setTextSize(9);b.setTextColor(NAVY);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackgroundColor(Color.TRANSPARENT);String pg=x.substring(x.indexOf("  ")+2);if(pg.equals("Current"))pg="Current Affairs";final String target=pg;b.setOnClickListener(v->page(target));b.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN)press(v);return false;});nav.addView(b,new LinearLayout.LayoutParams(0,58,1));}root.addView(nav);setContentView(root);page("Home");}
    void page(String p){body.removeAllViews();topTitle(p);if(p.equals("Home")){hero("TODAY'S MISSION","Maths • Number System","30 min Theory  •  15 min Practice  •  10 min Revision",v->lesson("Number System"));statRow();section("QUICK START");action("📐  Continue Maths — Number System",v->lesson("Number System"));action("🧠  10 Question Practice",v->practice());action("🤖  Ask Fighter AI",v->fighter());action("📕  Mistake Book",v->mistakes());action("📤  Share Warrior Aspirants",v->shareApp());}else if(p.equals("Study")){card("STUDY ROOM","SSC CGL  •  Railway  •  UP SI","Theory → Examples → Practice → PYQ → Revision");subject("📐","Maths","Beginner → Advanced",v->topics("Maths"));subject("🧠","Reasoning","Concepts + patterns + speed",v->topics("Reasoning"));subject("🔤","English","Grammar + vocabulary + comprehension",v->topics("English"));subject("🌍","GK / GS","History • Geography • Polity • Science",v->topics("GK / GS"));}else if(p.equals("Practice")){hero("PRACTICE ARENA","Train your speed & accuracy","10 / 20 / 50 questions  •  Timer  •  Analysis",v->practice());action("⚡  Quick Practice — 10 Questions",v->practice());action("🎯  Topic Practice",v->topics("Practice Topics"));action("📚  PYQ Engine",v->pyq());action("🏆  Mock Test",v->mock());action("📕  Mistake Book",v->mistakes());}else if(p.equals("Current Affairs")){card("CURRENT AFFAIRS","Daily  •  Weekly  •  Monthly","Fresh verified updates will plug into this module.");action("📅  Daily Current Affairs",v->ca("Daily Current Affairs"));action("📚  Weekly Revision",v->ca("Weekly Revision"));action("🗓  Monthly One-Liners",v->ca("Monthly One-Liners"));action("❓  Daily Quiz",v->ca("Current Affairs Quiz"));}else{card("WARRIOR PROFILE","Level "+store.level()+"  •  XP "+store.xp(),"SSC CGL 2027  •  Railway  •  UP SI");action("⚙️  Preparation Settings",v->settings());action("📊  My Progress",v->progress());}}
    void topTitle(String p){LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(2,2,2,12);TextView t=text(p,25,NAVY,true);bar.addView(t,new LinearLayout.LayoutParams(0,52,1));TextView xp=text("⚔ "+store.xp()+" XP",12,RED,true);xp.setGravity(Gravity.CENTER);xp.setBackground(shape(Color.rgb(255,238,239),18));bar.addView(xp,new LinearLayout.LayoutParams(82,38));body.addView(bar);}
    void statRow(){LinearLayout row=new LinearLayout(this);row.setWeightSum(3);stat(row,"PREP",store.prep()+"%");stat(row,"ACCURACY",store.accuracy()+"%");stat(row,"STREAK","🔥 "+store.streak());body.addView(row,new LinearLayout.LayoutParams(-1,82));animateView(row,100);}
    void stat(LinearLayout row,String h,String v){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);c.setBackground(stroke(WHITE,Color.rgb(232,235,242),18));c.addView(text(h,9,MUTED,true));TextView n=text(v,18,NAVY,true);n.setGravity(Gravity.CENTER);c.addView(n);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,78,1);p.setMargins(3,0,3,0);row.addView(c,p);}
    void shareApp(){android.content.Intent i=new android.content.Intent(android.content.Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(android.content.Intent.EXTRA_SUBJECT,"Warrior Aspirants — Exam Preparation App");i.putExtra(android.content.Intent.EXTRA_TEXT,"Warrior Aspirants\nSSC CGL • Railway • UP SI\nLearn → Practice → Analyze → Improve → Achieve\nhttps://github.com/vinaykr13/warrior-aspirants");startActivity(android.content.Intent.createChooser(i,"Share Warrior Aspirants"));}
    void section(String s){TextView t=text(s,12,RED,true);t.setPadding(4,18,4,6);body.addView(t);}
    void card(String h,String sub,String val){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(14,12,14,13);c.setBackground(stroke(WHITE,Color.rgb(230,233,240),24));c.setElevation(3);c.addView(text(h,11,RED,true));c.addView(text(sub,17,DARK,true));c.addView(text(val,12,MUTED,false));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,3,0,9);body.addView(c,p);animateView(c,body.getChildCount()*24);}
    void hero(String h,String title,String sub,View.OnClickListener l){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(16,15,16,15);c.setBackground(shape(NAVY,26));c.setElevation(5);c.addView(text(h,11,Color.rgb(190,201,225),true));c.addView(text(title,20,WHITE,true));c.addView(text(sub,12,Color.rgb(215,222,238),false));Button go=new Button(this);go.setText("START MISSION  →");go.setTextSize(11);go.setTextColor(WHITE);go.setAllCaps(false);go.setBackground(shape(RED,18));go.setOnClickListener(l);LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,46);gp.setMargins(0,12,0,0);c.addView(go,gp);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,2,0,10);body.addView(c,p);animateView(c,60);}
    void subject(String icon,String name,String sub,View.OnClickListener l){LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(10,8,8,8);c.setBackground(stroke(WHITE,Color.rgb(230,233,240),22));c.setElevation(2);TextView i=text(icon,24,RED,true);i.setGravity(Gravity.CENTER);c.addView(i,new LinearLayout.LayoutParams(52,68));TextView n=text(name+"\n"+sub,16,DARK,true);c.addView(n,new LinearLayout.LayoutParams(0,68,1));TextView go=text("›",30,RED,true);go.setGravity(Gravity.CENTER);c.addView(go,new LinearLayout.LayoutParams(48,68));c.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,76);p.setMargins(0,5,0,5);body.addView(c,p);animateView(c,body.getChildCount()*25);}
    void topics(String s){body.removeAllViews();topTitle(s+"  •  Topics");if(s.equals("Maths")){topic("01","Number System","Basics, divisibility, HCF / LCM",v->lesson("Number System"));topic("02","Percentage","Basic %, increase / decrease",v->lesson("Percentage"));topic("03","Ratio & Proportion","Ratio, proportion and applications",v->lesson("Ratio & Proportion"));topic("04","Average","Mean and weighted average",v->lesson("Average"));topic("05","Profit & Loss","CP, SP, profit / loss percentage",v->lesson("Profit & Loss"));topic("06","Time & Work","Work efficiency and combined work",v->lesson("Time & Work"));topic("07","Time, Speed & Distance","Speed, distance and trains",v->lesson("Time, Speed & Distance"));topic("08","Algebra","Identities and basic equations",v->lesson("Algebra"));topic("09","Geometry & Mensuration","Lines, angles, triangles, areas",v->lesson("Geometry & Mensuration"));topic("10","Trigonometry","Ratios and standard values",v->lesson("Trigonometry"));}else if(s.equals("Reasoning")){topic("01","Analogy","Find the same relationship",v->lesson("Analogy"));topic("02","Classification","Find the odd one out",v->lesson("Classification"));topic("03","Series","Number, alphabet and figure series",v->lesson("Series"));topic("04","Coding-Decoding","Letter / number coding patterns",v->lesson("Coding-Decoding"));topic("05","Blood Relation","Family relationship problems",v->lesson("Blood Relation"));topic("06","Direction & Distance","Directions and shortest path",v->lesson("Direction & Distance"));topic("07","Syllogism","Statements and conclusions",v->lesson("Syllogism"));topic("08","Venn Diagram","Set relationships",v->lesson("Venn Diagram"));}else if(s.equals("English")){topic("01","Parts of Speech","Noun, pronoun, verb, adjective...",v->lesson("Parts of Speech"));topic("02","Tenses","Present, past and future",v->lesson("Tenses"));topic("03","Subject-Verb Agreement","Correct verb with subject",v->lesson("Subject-Verb Agreement"));topic("04","Articles","A, An, The",v->lesson("Articles"));topic("05","Prepositions","Usage and common errors",v->lesson("Prepositions"));topic("06","Active & Passive Voice","Voice transformation",v->lesson("Active & Passive Voice"));topic("07","Narration","Direct and indirect speech",v->lesson("Narration"));topic("08","Error Detection","Grammar-based errors",v->lesson("Error Detection"));}else{topic("01","History","Ancient, Medieval, Modern India",v->lesson("History"));topic("02","Geography","India and world geography",v->lesson("Geography"));topic("03","Polity","Constitution and governance",v->lesson("Polity"));topic("04","Economy","Basic economic concepts",v->lesson("Economy"));topic("05","Physics","Motion, work, energy, electricity",v->lesson("Physics"));topic("06","Chemistry","Matter, atoms, reactions",v->lesson("Chemistry"));topic("07","Biology","Cells, human body, plants",v->lesson("Biology"));}action("←  Back to Study",v->page("Study"));}
    void topic(String no,String name,String sub,View.OnClickListener l){LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(9,5,9,5);c.setBackground(stroke(WHITE,Color.rgb(230,233,240),20));TextView num=text(no,11,RED,true);num.setGravity(Gravity.CENTER);num.setBackground(shape(Color.rgb(255,240,241),14));c.addView(num,new LinearLayout.LayoutParams(46,54));TextView n=text(name+"\n"+sub,15,DARK,true);c.addView(n,new LinearLayout.LayoutParams(0,62,1));TextView b=text("OPEN  ›",10,RED,true);b.setGravity(Gravity.CENTER);c.addView(b,new LinearLayout.LayoutParams(70,62));c.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,70);p.setMargins(0,5,0,5);body.addView(c,p);animateView(c,body.getChildCount()*18);}
    void lesson(String topic){body.removeAllViews();topTitle(topic);card("LESSON","Theory + Example + Trick + Practice","Beginner-friendly explanation. Read → understand → solve.");body.addView(text("THEORY",12,RED,true));body.addView(text(theory(topic),15,DARK,false));body.addView(text("WORKED EXAMPLE",12,RED,true));body.addView(text(example(topic),15,DARK,false));body.addView(text("QUICK TRICK",12,RED,true));body.addView(text(trick(topic),15,DARK,false));action("▶  Start Practice",v->practiceTopic(topic));action("🎯  Open PYQs",v->pyqTopic(topic));action("←  Back",v->topics(topic.equals("Maths")?"Maths":topic.equals("Reasoning")?"Reasoning":topic.equals("English")?"English":"GK / GS"));}
    StudyContent.Lesson material(String topic){return StudyContent.get(topic);} String theory(String t){return material(t).theory;} String example(String t){return material(t).example;} String trick(String t){return material(t).trick;}
    void practice(){practiceTopic("Mixed Practice");}
    void practiceTopic(String topic){body.removeAllViews();topTitle("Practice");hero("QUESTION 1","20% of 250 = ?","Choose the correct answer and earn XP.",v->toast("Select an option below"));String[] o={"25","40","50","60"};for(String x:o){final String ans=x;action(ans,v->{if(ans.equals("50")){store.addResult(true);mistakes=store.mistakes();toast("Correct! +10 XP • Progress saved");}else{store.addResult(false);store.saveMistake(topic+" — 20% of 250");mistakes=store.mistakes();toast("Wrong • Added to Mistake Book");}});}action("Next Question  →",v->toast("More questions will load here."));}
    void pyq(){body.removeAllViews();topTitle("PYQ Engine");card("QUESTION BANK","Exam • Year • Subject • Topic","Verified PYQs with source, answer and explanation.");action("SSC CGL → Maths",v->pyqTopic("Maths"));action("SSC CGL → Reasoning",v->pyqTopic("Reasoning"));action("SSC CGL → English",v->pyqTopic("English"));action("SSC CGL → General Awareness",v->pyqTopic("GK / GS"));}
    void pyqTopic(String t){body.removeAllViews();topTitle("PYQ • "+t);card("TOPIC BANK","Previous-year questions","Year, shift / source, options, verified answer and explanation.");action("▶  Start Topic PYQ",v->practiceTopic(t));action("←  Back",v->pyq());}
    void mock(){body.removeAllViews();topTitle("Mock Tests");hero("FULL MOCK","SSC CGL-style practice","Timer • section analysis • accuracy • mistakes",v->practiceTopic("Mock Test"));action("🏆  Start Demo Mock",v->practiceTopic("Mock Test"));action("←  Back",v->page("Practice"));}
    void mistakes(){body.removeAllViews();topTitle("Mistake Book");if(mistakes.size()==0)card("EMPTY","No mistakes saved yet","Wrong practice questions will appear here automatically.");else for(String m:mistakes)card("REVISE",m,"Open question → understand → retry");action("←  Back",v->page("Practice"));}
    void fighter(){body.removeAllViews();topTitle("Fighter AI");hero("YOUR STUDY PARTNER","Explain • Solve • Quiz • Revise","Ask in simple Hindi / Hinglish.",v->toast("Type your question below"));EditText e=new EditText(this);e.setHint("Ask Fighter...");e.setTextSize(15);e.setPadding(18,5,18,5);e.setBackground(stroke(WHITE,Color.rgb(225,229,237),20));body.addView(e,new LinearLayout.LayoutParams(-1,58));action("Send  →",v->toast("Fighter backend will connect when AI API is added."));}
    void ca(String s){body.removeAllViews();topTitle(s);card("CONTENT MODULE","Fresh verified updates","This screen is ready for the live content pipeline. Facts should be sourced and dated.");action("←  Back",v->page("Current Affairs"));}
    void settings(){body.removeAllViews();topTitle("Settings");card("TARGET EXAMS","SSC CGL 2027","Railway • UP SI");card("DAILY TARGET","2 hours","Can be expanded to a personalised planner.");action("🗑  Reset saved progress",v->{new AlertDialog.Builder(this).setTitle("Reset progress?").setMessage("XP, solved questions and Mistake Book will be cleared on this device.").setNegativeButton("Cancel",null).setPositiveButton("Reset",(d,w)->{getSharedPreferences("warrior_progress",MODE_PRIVATE).edit().clear().apply();store=new ProgressStore(this);mistakes=store.mistakes();toast("Progress reset");page("Profile");}).show();});action("←  Back",v->page("Profile"));}
    void progress(){body.removeAllViews();topTitle("My Progress");card("LEVEL "+store.level(),"XP "+store.xp(),"Preparation "+store.prep()+"% • Accuracy "+store.accuracy()+"% • Streak "+store.streak()+" days");card("LEARNING LOOP","Learn → Practice → Analyze → Improve","Your XP, solved questions and Mistake Book are saved on this device.");action("←  Back",v->page("Profile"));}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}