package com.warrioraspirants.app;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.Typeface;import android.view.*;import android.widget.*;import android.graphics.drawable.GradientDrawable;

public class MainActivity extends Activity {
 int navy=Color.rgb(11,23,54),red=Color.rgb(214,40,40),white=Color.WHITE; LinearLayout root,content;
 public void onCreate(Bundle b){super.onCreate(b);splash();}
 TextView tv(String s,float z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setPadding(18,9,18,9);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
 GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
 void splash(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setGravity(17);l.setBackgroundColor(navy);TextView a=tv("WARRIOR ASPIRANTS",30,white,true),q=tv("Build the Empire.\nThe Queen Will Come.",18,Color.LTGRAY,true);q.setGravity(17);l.addView(a);l.addView(q);setContentView(l);a.setAlpha(0);q.setAlpha(0);a.animate().alpha(1).setDuration(700);q.animate().alpha(1).setStartDelay(400).setDuration(700);new Handler().postDelayed(this::home,2200);}
 void home(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(246,247,250));LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(14,16,14,8);h.setBackgroundColor(navy);h.addView(tv("WARRIOR ASPIRANTS",23,white,true));h.addView(tv("Learn • Practice • Analyze • Improve",14,Color.LTGRAY,false));root.addView(h);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(14,10,14,8);ScrollView s=new ScrollView(this);s.addView(content);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(white);String[] n={"Home","Study","Practice","Current Affairs","Profile"};for(String x:n){Button b=new Button(this);b.setText(x);b.setTextSize(10);b.setAllCaps(false);b.setOnClickListener(v->page(x));nav.addView(b,new LinearLayout.LayoutParams(0,62,1));}root.addView(nav);setContentView(root);page("Home");}
 void page(String p){content.removeAllViews();content.addView(tv(p,25,navy,true));
 if(p.equals("Home")){card("TODAY'S MISSION","Maths 60 min • Reasoning 45 min • English 45 min • GK/GS 30 min");card("WARRIOR PROGRESS","Preparation 0%   •   Streak 0 days\nAccuracy —   •   Level 1   •   XP 0");card("POWER HUB","📚 Study Room    📝 Practice\n🎯 PYQ Engine     🧠 Fighter AI\n🏆 Mock Tests     🔄 Revision");}
 else if(p.equals("Study")){button("📐 Maths — Basic → Advanced","Maths",true);button("🧠 Reasoning — Basic → Advanced","Reasoning",true);button("🔤 English — Grammar + Vocabulary","English",true);button("🌍 GK / GS — Static + Science","GK / GS",true);button("📰 Current Affairs — Daily → Monthly","Current Affairs",true);}
 else if(p.equals("Practice")){button("⚡ Quick Practice — 10 Questions","Quick Practice",false);button("🎯 Topic Practice — Weak Areas","Topic Practice",false);button("📜 PYQ Engine — Exam + Year + Topic","PYQ",false);button("🏆 Full Mock Test","Mock Test",false);button("📕 Mistake Book — Wrong Questions","Mistake Book",false);}
 else if(p.equals("Current Affairs")){button("📅 Daily Current Affairs","Daily CA",false);button("📚 Weekly Revision","Weekly CA",false);button("🗓 Monthly One-Liners","Monthly CA",false);button("❓ Current Affairs Quiz","CA Quiz",false);}
 else {card("WARRIOR PROFILE","Level 1 • XP 0 • Streak 0 days\nTarget: SSC CGL • Railway • UP SI");button("⚙️ Preparation Settings","Settings",false);}
 }
 void button(String h,String key,boolean study){Button b=new Button(this);b.setText(h);b.setAllCaps(false);b.setTextSize(15);b.setGravity(Gravity.CENTER_VERTICAL);b.setBackground(bg(white,24));b.setOnClickListener(v->detail(key));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,70);lp.setMargins(0,6,0,6);content.addView(b,lp);}
 void detail(String k){content.removeAllViews();content.addView(tv(k,24,navy,true));
 if(k.equals("Maths")){card("MATHS ROADMAP","1. Number System\n2. Simplification\n3. Percentage\n4. Ratio & Proportion\n5. Average\n6. Profit & Loss\n7. SI/CI\n8. Time & Work\n9. Time, Speed & Distance\n10. Algebra\n11. Geometry\n12. Mensuration\n13. Trigonometry\n14. Data Interpretation");card("LEARNING FLOW","Concept → Example → Shortcut → Practice → PYQ → Revision");}
 else if(k.equals("Reasoning"))card("REASONING ROADMAP","Analogy • Classification • Series • Coding-Decoding • Blood Relation • Direction • Ranking • Syllogism • Venn Diagram • Non-Verbal Reasoning");
 else if(k.equals("English"))card("ENGLISH ROADMAP","Parts of Speech • Tenses • Subject-Verb Agreement • Articles • Prepositions • Voice • Narration • Error Detection • Vocabulary • Cloze Test • Reading Comprehension");
 else if(k.equals("GK / GS"))card("GK / GS ROADMAP","History • Geography • Polity • Economy • Physics • Chemistry • Biology • Static GK • Environment");
 else if(k.equals("PYQ"))card("PYQ ENGINE","Select Exam → Year → Subject → Topic\nThen solve with answer, explanation, shortcut and difficulty.");
 else if(k.equals("Mistake Book"))card("MISTAKE BOOK","Your incorrect questions will appear here for focused revision.");
 else if(k.equals("Mock Test"))card("MOCK TESTS","SSC CGL Pattern • Sectional Test • Full Test\nTimer • Score • Accuracy • Time Analysis");
 else if(k.equals("Quick Practice")||k.equals("Topic Practice"))card("PRACTICE","Choose 10 / 20 / 50 questions\nDifficulty: Easy / Moderate / Hard\nSpeed + Accuracy + Detailed Solutions");
 else if(k.equals("Daily CA")||k.equals("Weekly CA")||k.equals("Monthly CA")||k.equals("CA Quiz"))card("CURRENT AFFAIRS","Content module ready. Live/current data will be connected in the next integration phase.");
 else if(k.equals("Settings"))card("PREPARATION SETTINGS","Target Exam • Daily Study Hours • Preferred Language • Notifications");
 else card("FIGHTER AI","Ask Fighter to explain a question, teach a topic, analyze mistakes, create a quiz, or revise a concept.\n\nAI backend connection will be added in the next phase.");
 Button back=new Button(this);back.setText("← Back");back.setOnClickListener(v->page("Home"));content.addView(back);}
 void card(String h,String body){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(10,10,10,10);c.setBackground(bg(white,26));c.setElevation(3);c.addView(tv(h,16,red,true));c.addView(tv(body,15,Color.DKGRAY,false));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,7,0,7);content.addView(c,lp);}
}