import 'dart:math' as math;
import 'package:flutter/material.dart';

void main()=>runApp(const WarriorAspirantApp());

class C{
 static const navy=Color(0xFF0A0E17),navy2=Color(0xFF0F172A),surface=Color(0xFF161F30),border=Color(0xFF334155),gold=Color(0xFFF59E0B),goldDark=Color(0xFFD97706),cyan=Color(0xFF38BDF8),orange=Color(0xFFF97316),white=Color(0xFFF8FAFC),muted=Color(0xFF94A3B8);
}
class WarriorAspirantApp extends StatelessWidget{
 const WarriorAspirantApp({super.key});
 Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Warrior Aspirant',theme:ThemeData(brightness:Brightness.dark,scaffoldBackgroundColor:C.navy,fontFamily:'Inter',useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:C.gold,brightness:Brightness.dark)),home:const Shell());
}
class Shell extends StatefulWidget{const Shell({super.key});State<Shell> createState()=>_Shell();}
class _Shell extends State<Shell> with SingleTickerProviderStateMixin{
 int tab=0;late AnimationController a;
 void initState(){super.initState();a=AnimationController(vsync:this,duration:const Duration(milliseconds:900))..forward();}
 void dispose(){a.dispose();super.dispose();}
 Widget build(BuildContext c){final pages=[Home(a),const Simple('Arena','Tests & Mock Battles',Icons.sports_martial_arts_rounded),const Simple('Armory','Notes, formulas & saved material',Icons.inventory_2_rounded),const Simple('Leaderboard','Track your warrior progress',Icons.emoji_events_rounded),const Simple('Profile','Your CGL preparation profile',Icons.person_rounded)];return Scaffold(body:IndexedStack(index:tab,children:pages),bottomNavigationBar:Nav(tab,(i){setState(()=>tab=i);a..reset()..forward();}));}
}
class Home extends StatelessWidget{
 final AnimationController a;const Home(this.a,{super.key});
 Animation<double> f(int n)=>CurvedAnimation(parent:a,curve:Interval(math.min(.05+n*.1,.72),math.min(.48+n*.1,.98),curve:Curves.easeOutCubic));
 Widget e(int n,Widget w){final q=f(n);return FadeTransition(opacity:q,child:SlideTransition(position:Tween(begin:const Offset(0,.08),end:Offset.zero).animate(q),child:w));}
 Widget build(BuildContext c)=>SafeArea(child:CustomScrollView(physics:const BouncingScrollPhysics(),slivers:[sp(e(0,const TopBar())),sp(e(1,const Pass())),sp(e(2,const Head('Strategic Arsenal','Master the core CGL subjects'))),sp(e(3,const Arsenal())),sp(e(4,const Head("Warrior's Training Ground",'Challenge yourself with timed battles'))),sp(e(5,const Mock()))]));
 Widget sp(Widget w)=>SliverPadding(padding:const EdgeInsets.fromLTRB(18,16,18,0),sliver:SliverToBoxAdapter(child:w));
}
class TopBar extends StatelessWidget{
 const TopBar({super.key});
 Widget build(BuildContext c)=>Row(children:[Container(width:50,height:50,decoration:BoxDecoration(gradient:const LinearGradient(colors:[C.gold,C.goldDark]),borderRadius:BorderRadius.circular(16),boxShadow:[BoxShadow(color:C.gold,blurRadius:18,spreadRadius:-12)]),child:const Icon(Icons.shield_rounded,color:C.navy,size:28)),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('WARRIOR ASPIRANT',style:TextStyle(color:C.gold,fontSize:11,fontWeight:FontWeight.w800,letterSpacing:1.5)),SizedBox(height:4),Text('Hello, Aathvik!',style:TextStyle(color:C.white,fontSize:20,fontWeight:FontWeight.w800)),SizedBox(height:2),Text('Target CGL',style:TextStyle(color:C.muted,fontSize:12))])),Tap(()=>ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('No new notifications'),behavior:SnackBarBehavior.floating)),Container(width:48,height:48,decoration:BoxDecoration(color:C.surface,borderRadius:BorderRadius.circular(15),border:Border.all(color:C.border)),child:const Icon(Icons.notifications_none_rounded,color:C.white)))]);
}
class Pass extends StatefulWidget{const Pass({super.key});State<Pass> createState()=>_Pass();}
class _Pass extends State<Pass> with SingleTickerProviderStateMixin{
 late AnimationController p;
 void initState(){super.initState();p=AnimationController(vsync:this,duration:const Duration(milliseconds:1900))..repeat(reverse:true);}
 void dispose(){p.dispose();super.dispose();}
 Widget build(BuildContext c)=>AnimatedBuilder(animation:p,builder:(c,w)=>Container(decoration:BoxDecoration(borderRadius:BorderRadius.circular(22),boxShadow:[BoxShadow(color:C.gold.withOpacity(.1+p.value*.1),blurRadius:8+p.value*12)]),child:w),child:Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF202D43),Color(0xFF0D1B32)]),borderRadius:BorderRadius.circular(22),border:Border.all(color:C.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:7),decoration:BoxDecoration(color:C.gold.withOpacity(.13),borderRadius:BorderRadius.circular(11),border:Border.all(color:C.gold.withOpacity(.3))),child:const Row(children:[Icon(Icons.workspace_premium_rounded,color:C.gold,size:16),SizedBox(width:6),Text('WARRIOR OF THE WEEK',style:TextStyle(color:C.gold,fontSize:9,fontWeight:FontWeight.w900,letterSpacing:.8))])),const Spacer(),const Text('LEVEL 12',style:TextStyle(color:C.cyan,fontSize:11,fontWeight:FontWeight.w800))]),const SizedBox(height:18),const Row(crossAxisAlignment:CrossAxisAlignment.end,children:[Text('78%',style:TextStyle(color:C.white,fontSize:34,fontWeight:FontWeight.w900)),SizedBox(width:8),Padding(padding:EdgeInsets.only(bottom:6),child:Text('DONE',style:TextStyle(color:C.muted,fontSize:11,fontWeight:FontWeight.w800,letterSpacing:1))),Spacer(),Text('1,240 XP',style:TextStyle(color:C.gold,fontSize:12,fontWeight:FontWeight.w800))]),const SizedBox(height:11),ClipRRect(borderRadius:const BorderRadius.all(Radius.circular(99)),child:const LinearProgressIndicator(value:.78,minHeight:8,backgroundColor:Color(0xFF263449),valueColor:AlwaysStoppedAnimation(C.gold))),const SizedBox(height:10),const Row(children:[Icon(Icons.bolt_rounded,color:C.orange,size:17),SizedBox(width:5),Text('Remaining MCQs',style:TextStyle(color:C.muted,fontSize:12)),Spacer(),Text('220',style:TextStyle(color:C.white,fontSize:12,fontWeight:FontWeight.w800))])])));}
}
class Head extends StatelessWidget{final String t,s;const Head(this.t,this.s,{super.key});Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(top:24,bottom:10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(color:C.white,fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:4),Text(s,style:const TextStyle(color:C.muted,fontSize:12))]));}
class Subject{final String name,count;final IconData icon;final Color color;const Subject(this.name,this.count,this.icon,this.color);}
const subjects=[Subject('Quantitative Maths','28 Chapters',Icons.calculate_rounded,C.cyan),Subject('Reasoning Ability','24 Chapters',Icons.psychology_rounded,Color(0xFFA78BFA)),Subject('General Awareness','32 Chapters',Icons.public_rounded,C.orange),Subject('English Comprehension','26 Chapters',Icons.menu_book_rounded,C.gold)];
class Arsenal extends StatelessWidget{const Arsenal({super.key});Widget build(BuildContext c)=>GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:subjects.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.14),itemBuilder:(c,i){final s=subjects[i];return Tap(()=>ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(s.name),behavior:SnackBarBehavior.floating)),Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:C.surface,borderRadius:BorderRadius.circular(20),border:Border.all(color:C.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:43,height:43,decoration:BoxDecoration(color:s.color.withOpacity(.12),borderRadius:BorderRadius.circular(13),border:Border.all(color:s.color.withOpacity(.24))),child:Icon(s.icon,color:s.color)),const Spacer(),Text(s.name,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:C.white,fontSize:14,fontWeight:FontWeight.w800)),const SizedBox(height:5),Text(s.count,style:const TextStyle(color:C.muted,fontSize:10,fontWeight:FontWeight.w600))]));});}}
class Mock extends StatelessWidget{const Mock({super.key});Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:C.surface,borderRadius:BorderRadius.circular(22),border:Border.all(color:C.border)),child:Column(children:[Row(children:[Container(width:46,height:46,decoration:BoxDecoration(gradient:const LinearGradient(colors:[C.orange,C.goldDark]),borderRadius:BorderRadius.circular(14)),child:const Icon(Icons.flash_on_rounded,color:C.navy)),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Live(),SizedBox(width:8),Text('CGL TIER-1',style:TextStyle(color:C.muted,fontSize:9,fontWeight:FontWeight.w900,letterSpacing:1))]),SizedBox(height:6),Text('Mega Mock Battle',style:TextStyle(color:C.white,fontSize:18,fontWeight:FontWeight.w900))]))]),const SizedBox(height:18),const Row(children:[Icon(Icons.timer_outlined,color:C.cyan,size:17),SizedBox(width:5),Text('60 min',style:TextStyle(color:C.muted,fontSize:11)),SizedBox(width:18),Icon(Icons.quiz_outlined,color:C.cyan,size:17),SizedBox(width:5),Text('100 Questions',style:TextStyle(color:C.muted,fontSize:11)),Spacer(),Text('+500 XP',style:TextStyle(color:C.gold,fontSize:11,fontWeight:FontWeight.w900))]),const SizedBox(height:18),Shine(onTap:null)]));}
class Live extends StatelessWidget{const Live({super.key});Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(horizontal:7,vertical:4),decoration:BoxDecoration(color:C.orange.withOpacity(.12),borderRadius:BorderRadius.circular(7),border:Border.all(color:C.orange.withOpacity(.35))),child:const Text('LIVE',style:TextStyle(color:C.orange,fontSize:8,fontWeight:FontWeight.w900)));}
class Shine extends StatefulWidget{final VoidCallback? onTap;const Shine({super.key,required this.onTap});State<Shine> createState()=>_Shine();}
class _Shine extends State<Shine> with SingleTickerProviderStateMixin{late AnimationController c;void initState(){super.initState();c=AnimationController(vsync:this,duration:const Duration(milliseconds:1800))..repeat();}void dispose(){c.dispose();super.dispose();}Widget build(BuildContext x)=>AnimatedBuilder(animation:c,builder:(x,_)=>
CustomPaint(painter:Glow(c.value),child:InkWell(onTap:widget.onTap??(){},borderRadius:BorderRadius.circular(15),child:Container(height:50,alignment:Alignment.center,decoration:BoxDecoration(color:C.navy2,borderRadius:BorderRadius.circular(15)),child:const Row(mainAxisAlignment:MainAxisAlignment.center,children:[Text('TAKE TEST',style:TextStyle(color:C.gold,fontSize:12,fontWeight:FontWeight.w900,letterSpacing:1.2)),SizedBox(width:8),Icon(Icons.arrow_forward_rounded,color:C.gold,size:18)]))));}
class Glow extends CustomPainter{final double t;Glow(this.t);void paint(Canvas c,Size s){final r=RRect.fromRectAndRadius(Offset.zero&s,const Radius.circular(15));final p=Paint()..style=PaintingStyle.stroke..strokeWidth=1.5..shader=SweepGradient(transform:GradientRotation(t*math.pi*2),colors:const[C.goldDark,C.cyan,C.gold,C.goldDark]).createShader(Offset.zero&s);c.drawRRect(r,p);}bool shouldRepaint(covariant Glow o)=>o.t!=t;}
class Tap extends StatefulWidget{final VoidCallback onTap;final Widget child;const Tap(this.onTap,this.child,{super.key});State<Tap> createState()=>_Tap();}
class _Tap extends State<Tap>{bool down=false;Widget build(BuildContext c)=>GestureDetector(behavior:HitTestBehavior.opaque,onTapDown:(_)=>setState(()=>down=true),onTapCancel:()=>setState(()=>down=false),onTapUp:(_){setState(()=>down=false);widget.onTap();},child:AnimatedScale(scale:down?.965:1,duration:const Duration(milliseconds:100),child:widget.child));}
class Nav extends StatelessWidget{final int i;final ValueChanged<int> on;const Nav(this.i,this.on,{super.key});static const data=[(Icons.home_rounded,'Home'),(Icons.sports_martial_arts_rounded,'Arena'),(Icons.inventory_2_rounded,'Armory'),(Icons.leaderboard_rounded,'Leaderboard'),(Icons.person_rounded,'Profile')];Widget build(BuildContext c)=>Container(decoration:const BoxDecoration(color:Color(0xFF0C1320),border:Border(top:BorderSide(color:C.border))),child:SafeArea(top:false,child:Padding(padding:const EdgeInsets.all(8),child:Row(children:List.generate(data.length,(n){final a=i==n;return Expanded(child:Tap(()=>on(n),AnimatedContainer(duration:const Duration(milliseconds:260),margin:const EdgeInsets.symmetric(horizontal:3),padding:const EdgeInsets.symmetric(vertical:7),decoration:BoxDecoration(color:a?C.gold.withOpacity(.1):Colors.transparent,borderRadius:BorderRadius.circular(15),border:Border.all(color:a?C.gold.withOpacity(.28):Colors.transparent)),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(data[n].$1,color:a?C.gold:C.muted,size:21),const SizedBox(height:3),Text(data[n].$2,maxLines:1,overflow:TextOverflow.ellipsis,style:TextStyle(color:a?C.gold:C.muted,fontSize:9,fontWeight:a?FontWeight.w900:FontWeight.w600))])));}))));}
class Simple extends StatelessWidget{final String t,s;final IconData icon;const Simple(this.t,this.s,this.icon,{super.key});Widget build(BuildContext c)=>SafeArea(child:Center(child:Padding(padding:const EdgeInsets.all(28),child:Container(width:double.infinity,padding:const EdgeInsets.all(28),decoration:BoxDecoration(color:C.surface,borderRadius:BorderRadius.circular(22),border:Border.all(color:C.border)),child:Column(mainAxisSize:MainAxisSize.min,children:[Container(width:70,height:70,decoration:BoxDecoration(color:C.gold.withOpacity(.12),borderRadius:BorderRadius.circular(20)),child:Icon(icon,color:C.gold,size:34)),const SizedBox(height:18),Text(t,style:const TextStyle(color:C.white,fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:7),Text(s,textAlign:TextAlign.center,style:const TextStyle(color:C.muted,fontSize:13))]))));}
